README.md

Hey! Great library, excited to see where it goes. Made a small fix in the example.In the user model the class name was `Post`, changed it to `User`.

Fix error in example

---

src/Query.ts
src/Repo.ts
src/__test__/Repo.spec.ts

I've added sorting feature to Repo and Query class.
Take a look and tell me your opinion.

Add sorting feature (Repo.orderBy)

---

src/Query.ts
src/Repo.ts
test/unit/Repo_Retrieve.spec.js

#21 Return empty array instead of null when retrieving multiple records

---

docs/store/deleting-data.md
src/Query.ts
src/Repo.ts
src/modules/mutations.ts
src/modules/rootActions.ts
src/modules/subActions.ts
test/feature/RootModules.spec.js
test/feature/SubModules.spec.js
test/unit/Repo_Delete.spec.js

Fixes #24.
@kiaking Please review.

Added provision for deleting all data

---

docs/store/retrieving-data.md
src/Query.ts
src/Repo.ts
test/unit/Repo_Retrieve.spec.js

Add nested where clause feature

---

src/Query.ts

Updated Query class to use
```javascript
protected: records: Records
```
as the source of truth for each query instance allowing plugins and foreign methods to access results at run time.
#37 #39

Modify Query class to use Query.records for more dynamic workflow

---

docs/store/retrieving-data.md
src/Repo.ts
src/support/lodash.ts
test/unit/Repo_Aggregates.spec.js

Issue #45 
Adds `max` and `min` aggregate methods. Needs to update doc before merging.

#45 Add max and min aggregates

---

docs/getting-started.md

Issue: #42 
This PR adds note on defining property in the class.

Close #42 Add note about defining static property in the class

---

docs/README.md
docs/SUMMARY.md
docs/model.md
docs/model/attributes.md
docs/model/defining-models.md
src/Attributes/AttrTypes.ts
src/Attributes/Types.ts
src/Attributes/index.ts
src/Model.ts
src/Repo.ts
src/Schema.ts
src/index.cjs.ts
src/index.ts
src/modules/mutations.ts
src/modules/rootGetters.ts
src/modules/subGetters.ts
src/plugins/use.ts
src/repo/Incrementer.ts
src/repo/Query.ts
src/repo/Repo.ts
src/support/lodash.ts
test/feature/Plugin.spec.js
test/unit/Model.spec.js
test/unit/Repo_Aggregates.spec.js
test/unit/Repo_Create.spec.js
test/unit/Repo_Create_Attributes.spec.js
test/unit/Repo_Delete.spec.js
test/unit/Repo_Retrieve.spec.js
test/unit/Repo_Retrieve_Relations.spec.js
test/unit/Repo_Update.spec.js

Issue #38 
This PR adds auto increment feature.

#38 Add auto increment attribute

---

src/Model.ts
src/Schema.ts
src/repo/Incrementer.ts
src/repo/Query.ts
src/repo/Repo.ts
test/unit/Model.spec.js
test/unit/Model_Normalization.spec.js
test/unit/Repo_Create.spec.js
test/unit/Repo_Create_Attributes.spec.js
test/unit/Repo_Retrieve.spec.js
test/unit/Repo_Retrieve_Relations.spec.js

Issue #48 
This PR adds composition primary key feature.

#48 Implement composit primary key feature

---

docs/store/retrieving-data.md
src/repo/Query.ts
test/fixtures/models/User.js
test/unit/Repo_Retrieve.spec.js

Issue #19 
This PR enables where closure to access model instance.

#19 Pass model instance to the where closure

---

docs/README.md
docs/SUMMARY.md
docs/digging-deeper.md
docs/digging-deeper/query-class.md
src/repo/Query.ts
test/support/Helpers.js
test/unit/Query_Hooks.spec.js

Issue: #41 
This PR adds lifecycle hooks to the Query class.

#41 Add lifecycle hook to the Query class

---

docs/store/retrieving-data.md
src/repo/Query.ts
src/repo/Repo.ts
test/unit/repo/Repo_Retrieve.spec.js

Issue #62 
This PR adds `last` method that fetches the last item on the query chain.

#62 Add `last` method

---

docs/store/inserting-and-updating-data.md
src/modules/mutations.ts
src/modules/rootActions.ts
src/modules/subActions.ts
src/repo/Repo.ts
test/feature/Update.spec.js
test/unit/repo/Repo_Update.spec.js

Issue #79 
This PR makes `updated` method return updated record.

#79 Let `update` return updated records

---

docs/relationships/retrieving-relationships.md
src/repo/Repo.ts
test/unit/repo/repo/Repo_Retrieve_Relations.spec.js

Implement withAll and withAllRecursive methods

---

src/attributes/relations/BelongsTo.ts
src/attributes/relations/BelongsToMany.ts
src/attributes/relations/HasMany.ts
src/attributes/relations/HasManyBy.ts
src/attributes/relations/HasManyThrough.ts
src/attributes/relations/HasOne.ts
src/attributes/relations/MorphMany.ts
src/attributes/relations/MorphOne.ts
src/attributes/relations/MorphTo.ts
src/attributes/relations/MorphToMany.ts
src/attributes/relations/MorphedByMany.ts

fix: https://github.com/vuex-orm/vuex-orm/issues/111

fix: Return empty model object none related

---

src/attributes/relations/HasManyThrough.ts
test/feature/relations/Relations_HasManyThrough.spec.js
test/performance/Retrieve_HasManyThrough.spec.js

This pullrequest is performance uneasy
fix: https://github.com/vuex-orm/vuex-orm/issues/131

HasManyThrough Relation only last record

---

src/attributes/relations/MorphToMany.ts
src/attributes/relations/MorphedByMany.ts
test/feature/relations/Relations_MorphMany.spec.js
test/feature/relations/Relations_MorphToMany.spec.js

#142 Fix where pivot table is not being created

---

src/attributes/relations/BelongsTo.ts
src/attributes/relations/BelongsToMany.ts
src/attributes/relations/HasMany.ts
src/attributes/relations/HasManyBy.ts
src/attributes/relations/HasManyThrough.ts
src/attributes/relations/HasOne.ts
src/attributes/relations/MorphMany.ts
src/attributes/relations/MorphOne.ts
src/attributes/relations/MorphTo.ts
src/attributes/relations/MorphToMany.ts
src/attributes/relations/MorphedByMany.ts
src/attributes/relations/Relation.ts
src/data/processors/ProcessStrategy.ts
test/feature/relations/Retrieve_DeepLoad.spec.js
test/unit/query/Query_Create_MorphTo.spec.js

Issue #152
This PR fixes where belongs to relation returns record with default values when it should return `null`.

#152 Fix belongs to relation returns record with default values

---

src/attributes/relations/BelongsTo.ts
src/attributes/relations/HasMany.ts
src/attributes/relations/HasManyBy.ts
src/attributes/relations/HasOne.ts
test/performance/Retrieve_BelongsTo.spec.js

Issue #154 
This PR fixes the performance issue when loading lots of belongsTo relationship.

#154 Fix performance issue on belongsTo relationship loading

---

src/attributes/relations/HasMany.ts
test/feature/relations/HasMany.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/164

HasMany forEach error then set null

---

src/attributes/relations/BelongsTo.ts
src/attributes/relations/HasOne.ts
test/feature/relations/BelongsTo.spec.js
test/feature/relations/HasOne.spec.js

#157 Fix app crash when has one relationship has the value of null

---

src/attributes/types/Number.ts
test/feature/attributes/Number.spec.js

Issue #194
This PR fixes where floating number gets rounded when using `number` attribute.

#194 Fix where number attribute rounding the floating number

---

src/attributes/relations/BelongsToMany.ts
test/feature/relations/BelongsToMany.spec.js
test/unit/query/Query_Create_BelongsToMany.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/201
I will fix broken testcode.

Ignore create pivot record

---

docs/guide/store/retrieving-data.md
src/query/Query.ts
test/unit/query/Query_Aggregates.spec.js

Implements issue #209.
First contribution, hope everything is ok :)

Implement sum aggregate

---

src/schema/IdAttribute.ts
src/schema/ProcessStrategy.ts
test/feature/attributes/Increment.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/168

Incremnt nested object with childrent id of null

---

src/query/filters/WhereFilter.ts
test/feature/basics/Retrieve_Where.spec.js

This PR fixes bug  #225 and add test cases to prevent it from happening again

Fix for #225: nested where not handled in complex cases

---

src/query/Query.ts
test/feature/basics/Retrieve_SSRSupport.spec.js

Issue #242, #239 
Instantiate plain records to Model instance when fetching them.
I'll create example Nuxt application and see if this works as expected.

#242 Instantiate record when fetching them if they are not Model instance

---

docs/guide/advanced/interact-with-store-from-model.md
docs/guide/store/inserting-and-updating-data.md
src/model/Model.ts
src/modules/Actions.ts
src/modules/RootActions.ts
src/modules/RootMutations.ts
src/modules/payloads/RootActions.ts
src/modules/payloads/RootMutations.ts
src/query/Query.ts
test/feature/basics/New.spec.js

Issue #143
This PR adds `new` method that creates a fresh record with default values.

#143 Add `new` method

---

src/model/Model.ts
test/feature/models/Save.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/150
@kiaking 
I write the test code on the weekend.
Please teach if have better code or this have problem this code.

feat: save method to model class

---

docs/guide/components/models.md
src/attributes/types/Boolean.ts
src/attributes/types/Number.ts
src/attributes/types/String.ts
test/feature/attributes/Boolean.spec.js
test/feature/attributes/Number.spec.js
test/feature/attributes/String.spec.js
test/feature/relations/BelongsToMany_Retrieve.spec.js

Issue: #171
This PR adds `nullable` methods to the type attributes.

#171 Add `nullable` method to the type attributes

---

test/feature/relations/Retrieve_SelfRelation.spec.js

Issue raised at Slack. It is now not possible to load self relationship. I've created the failing test case. Not sure why this is not working. Need to look into it more.

Load self relationship

---

src/query/Query.ts
test/feature/basics/Update.spec.js
test/feature/relations/HasMany.spec.js

Issue #90
This PR will make `update` method work on updating primary key value of the record.

#90 Update state index value when a user updates the primary key value

---

src/attributes/relations/BelongsTo.ts
test/feature/relations/Retrieve_With.spec.js

fix: retrieving relation by empty key

---

src/attributes/relations/BelongsToMany.ts
test/feature/relations/BelongsToMany_Retrieve.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/282

belongsToMany is return [] if nothing references records

---

src/attributes/relations/HasMany.ts
test/feature/relations/HasMany.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/299
There is this same problem to other reference maybe.
But i not research. I will research before long.

resolve reference by localKey

---

src/attributes/relations/BelongsToMany.ts
test/feature/relations/BelongsToMany_Persist.spec.js

fix: https://github.com/vuex-orm/vuex-orm/issues/294
https://stackoverflow.com/questions/47103028/how-to-use-object-spread-with-nested-properties?rq=1
@bentleyo thank you for your testcode

fix: lost pivot record with field data

---

src/polyfills/index.ts

fix: https://github.com/vuex-orm/vuex-orm/issues/317
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

Object.assign is not defined in IE11

---

src/model/Model.ts
test/feature/relations/BelongsTo.spec.js

Issue: https://github.com/vuex-orm/vuex-orm/issues/320

create nested data with composite key

---

src/attributes/relations/BelongsToMany.ts
src/query/processors/Processor.ts
test/feature/relations/BelongsToMany_Persist.spec.js

#303 Fix belongs to many not working when creating data with `increment` id

---

src/query/Query.ts

Add string[] to Query.with name parameter

---

test/feature/relations/HasManyThrough.spec.js

Issue #352 
This PR tries to solve the issue #352. Added test case but it seems like passing.

#352 String id for Has Many Through relationship

---

docs/guide/prologue/getting-started.md

I have noticed that some methods return promises, it'd nice if the examples use await just to show that a promise is expected.
In addition I have created the following code that gets the model and injects models into the Vue prototype. Can be added as part of Vuex ORM somewhere.
```js
/**
* Map Vuex ORM models to computed properties to provide fluent Vuex ORM API out of the box
* run it in a Vue component as `computed: {...mapVuexORMModels(['modelName','modelName',...])}`
* @param models {Array} array of model names to map out
* @return {Object} mapped models instances
*/
function mapVuexORMModels(models) {
let mappedModels = {};
// create the Vuex mapGetters obj
for (let model of models) {
mappedModels[model] = function () {
// console.debug('context of this: ', this);
return …
```

Add information about models: Docs

---

src/attributes/relations/Relation.ts
test/feature/relations/BelongsToMany_Retrieve.spec.js

fix return empty model object when have not id for belongsToMany 

---

docs/.vuepress/config.js
docs/README.md
docs/guide/README.md
docs/guide/inheritance/defining-inheritance.md
docs/guide/inheritance/discriminator-field.md
docs/guide/inheritance/notes-on-cycles.md
src/database/Database.ts
src/database/Entity.ts
src/model/Model.ts
src/model/contracts/FieldCache.ts
src/model/contracts/InheritanceTypes.ts
src/query/Query.ts
src/query/loaders/Loader.ts
test/feature/inheritance/Model_Inheritance.spec.js
test/feature/inheritance/Model_Inheritance_CRUD.spec.js
test/feature/inheritance/Model_Inheritance_Discriminator.spec.js
test/feature/inheritance/Model_Inheritance_Relations.spec.js
test/unit/database/Database.spec.js
test/unit/model/Model.spec.js
test/unit/model/Model_Utilities.spec.js

Inheritance Handling

---

docs/guide/data/retrieving.md

Issue #402 
As discussed in the issue, this PR adds note in the documentation.

#402 Add note about returning falsy value in where clause

---

docs/guide/data/deleting.md

Issue #425
This PR adds `dispatch('entities/deleteAll')` method to the docs.

#425 Add dispatch('entities/deleteAll') to the docs

---

docs/guide/data/inserting-and-updating.md
docs/guide/model/defining-models.md

Documentation update discussed in #417

[Documentation] primary key and index key

---

src/model/Model.ts
src/query/contracts/Predicate.ts
test/feature/basics/Delete.spec.ts
test/feature/basics/Delete_Composite_Key.spec.ts

Issue #442
This PR fixes typing error on delete method.

#442 Fix type error for delete method

---

docs/guide/data/inserting-and-updating.md

Small typo I spotted while reading the docs

Fix small typo in the docs

---

docs/guide/prologue/getting-started.md

Double slash (//) error in importing Model

getting-started.md

---

src/query/loaders/Loader.ts

Issue #472 
This PR fixes the type error in Nuxt SSR.

#472 Fix Nuxt SSR throwing error due to array instanceof

---

docs/guide/data/inserting-and-updating.md

For "You may also pass an array of record." records should be plural.

Fix typo in insert doc

---

src/query/Query.ts
src/query/filters/OrderByFilter.ts
src/query/options/OrderKey.ts
src/query/options/Orders.ts
src/query/options/index.ts
src/support/Utils.ts
test/feature/basics/Retrieve_OrderBy.spec.js

Create OrderKey type, allow orderBy to take in function

---

src/query/Query.ts
test/feature/hooks/Local_Binding.spec.ts

Issue #344
This PR will bind local lifecycle hook to model object.

#344 Bind local hook to model object

---

docs/guide/model/relationships.md

`entities` should be `entity`.
`field` should be `fields`.

fix: Has Many By wrong words

---

docs/guide/data/retrieving.md

Found a typo in the docs while navigating through it. Hope it helps

Fixed Typo in docs

---

docs/api/model/model.md
src/attributes/Attribute.ts
src/attributes/types/Type.ts

PR for #513
Move a property of value to Attribute class from Type class.
And, document updated.
All tests passed, but I'm worried about the Relation class not broken...but, I couldn't verify it well. So I want someone to help.

Define default value of fields 

---

src/database/Database.ts
test/feature/basics/Update.spec.ts
test/feature/database/RegisterModel.spec.js
test/feature/modules/SubGetters_DirectEntityCall.spec.js

PR for #187
(#511 started from scratch)

register model at runtime

---

src/support/Utils.ts
test/feature/basics/Retrieve_OrderBy.spec.js
test/unit/support/Utils.spec.ts

Issue #543
Branched off of `v0.35.1` incase a minor patch release is possible considering this is a substantial issue.

Fixes orderBy bug

---

docs/guide/data/retrieving.md
src/model/Model.ts
src/query/Query.ts
test/feature/basics/Exists.spec.ts

Issue: https://github.com/vuex-orm/vuex-orm/issues/486
Hey,
Only the adjustments in the documentation are missing.
Are there preferences where the feature should be added to the documentation?

#486 exists query resolver

---

docs/guide/data/inserting-and-updating.md

Added an example to the guide to mention the possibility of updating multiple entries at once.
AFAIK this option of using the 'update' method is not mentioned anywhere yet. 
Fixed a few typos and grammatical errors elsewhere as well;

Added an example to the guide to mention the possibility of updating multiple entries at once

---

docs/guide/digging-deeper/vuex-module.md

Hi, i found little typo in your documentation

docs: fix typo
