README.md
Simple typo fix in documentation. Close square brackets.
=> Fix js typo (closing square brackets)

src/Repo.ts, src/__test__/Repo.spec.ts
When server API returns empty records (data: []), Repo.create couldn't update correctly.
After applying this PR, Repo.create updates empty data.
I also added tests and checked all tests passed.
=> Add empty data case of Repo.create

src/Query.ts, test/unit/Repo.spec.js
I found a degration from version 0.3.
Please take a look if my fix is correct.
=> Fix where clause to handle non string value

docs/README.md, docs/SUMMARY.md, docs/store/deleting-data.md, src/Query.ts, src/Repo.ts, src/modules/mutations.ts, src/modules/rootActions.ts, src/modules/subActions.ts, test/feature/RootModules.spec.js, test/feature/SubModules.spec.js, test/unit/Repo.spec.js
Issue: #11 
Add delete feature so we can delete data in the store. [Doc can be found at here](https://github.com/revolver-app/vuex-orm/blob/5591311664e77049204f79011565c2ae7bf99691/docs/store/deleting-data.md).
```js
// Delete data by the value of the primary key.
store.dispatch('entities/users/delete', 1)
// Delete by closure
store.dispatch('entities/users/delete', (record) => {
return record.id === 1 || record.name === 'Jane'
})
```
=> #11 Add delete feature

src/Query.ts, src/support/lodash.ts, test/unit/Repo_Retrieve.spec.js
Hi guys, great project! We were trying to `where` with a closure but were unable to access local variables;
```javascript
const ageAsVariable = 40
const result = Repo.query(state, 'users', false)
.where(r => r.age < ageAsVariable)
.get()
```
This would throw an error because the function is executed in the global scope (window) and the variable doesn't exist there. This PR fixes this.
I'm not used to writing TypeScript, so please correct any errors :)
=> Fix where closure scopes in global scope

src/Repo.ts, src/modules/mutations.ts, src/modules/rootActions.ts, test/feature/RootModules.spec.js
Issue: #30 
This PR makes `deleteAll` method work without payload.
@mastermunj, Sorry to bother you but I just wanted to check you in on this PR. It seems like this change makes it possible to use delete all method without an empty object.
Did you have any specific concern with implementation? The test is passing, but I wanted to make sure I'm not missing something.
May I ask you to review this code briefly 🙏 
```js
dispatch('entities/deleteAll') // Now this works.
dispatch('entities/deleteAll', {}) // This still works too.
```
=> #30 Enable deleteAll without payload

src/Model.ts, src/Repo.ts, test/fixtures/models/User.js, test/unit/Repo_Create.spec.js
Issue: #25, #29 
This PR makes `create` and `insert` action to fill missing model fields with default value when saving data to the store.
Now any field of data passed to `create` and `insert` action which doesn't exist in the Model's fields will be ignored.
```js
// When you have these fields.
class Users extends Model {
static fields () {
return {
id: this.attr(null),
name: this.attr('')
}
}
}
// And pass this kind of data.
store.dispatch('entities/users/create', {
data: {
id: 1,
age: 24
}
})
// This data will be saved to store. There is `name` but no `age` here.
{
id: 1,
name: ''
}
```
@CinKon Would you mind taking a look at the **Behavior Change**? Do you think this would be OK? or should I make non defined data (`age` in the above example) to be saved in the store?
=> #25 Fill missing fields with model's default value when creating new data

docs/store/retrieving-data.md, src/Query.ts, src/Repo.ts, test/unit/Repo_Retrieve.spec.js
Issue: #32 
This PR adds `has` and `hasNot` method as explained in issue #32.
=> #32 Add has and hasNot method to query depending on relationship existence and absence

docs/README.md, docs/SUMMARY.md, docs/plugins.md, src/Query.ts, src/index.cjs.ts, src/index.ts, src/plugins/use.ts, test/feature/Plugin.spec.js
Issue: #37 
This PR adds "plugin" feature to the Vuex ORM. It will enable 3rd party library to add new functionality to Vuex ORM.
A Vuex ORM plugin should be an object that exposes an `install` method. The method will be called with the Vuex ORM components such as Model, Repo, Query and such as the first argument, along with possible options.
```js
const plugin = {
// `components` contains Vuex ORM objects such as Model, Repo, or Query.
// The plugin author can then extend those objects to add whatever
// features it needs.
install (components, options) {
// Add global (static) method or property.
components.Model.globalMethod = function () {
// Logic...
}
// Add an instance method or property.
components.Repo.prototype.instanceMethod = function () {
// Logic...
}
}
}
```
Install the …
=> #37 Add the plugin feature

docs/store/inserting-and-updating-data.md, package.json, src/modules/mutations.ts, src/modules/rootActions.ts, src/modules/subActions.ts, src/repo/Repo.ts, src/repo/relations/BelongsToMany.ts, src/repo/relations/HasMany.ts, src/repo/relations/HasManyBy.ts, test/feature/RootModules.spec.js, test/feature/RootModules_Inserts.spec.js, test/feature/SubModules.spec.js, test/feature/SubModules_Inserts.spec.js
Issue #62 
This PR makes `create` and `insert` actions to return newly created objects. Doing kinda hacky solution here that passing Promise to the mutation and resolving inside mutation to get result back at action. Test is passing and it works. I think it wouldn't cause any problem...?
=> #62 Return newly created object from insert actions

test/feature/Relations_BelongsTo.spec.js
This test fails since 0.20.0 (works in 0.19.0).
=> Add test for belongsTo relation with nested entities

src/repo/Repo.ts
update with falsy id  such as 0 will be ignored right now
```js
dispatch('update', {
id: 0
// ...update data
})
```
=> Add support to update with falsy id

docs/relationships/retrieving-relationships.md, src/attributes/relations/Relation.ts, src/repo/Repo.ts, test/unit/repo/repo/Repo_Retrieve_Relations.spec.js
This PR depends on https://github.com/vuex-orm/vuex-orm/pull/106.
This PR adds with() syntax improvements:
- You can now write `with('posts.comments|reviews')` to fetch multiple sub relations
- You can now write `with('posts.*')` to fetch all sub relations of a relation
- You can now write `with('*')` as an alias for `withAll()` for consistency purposes
=> with() syntax improvements

docs/relationships/retrieving-relationships.md, src/attributes/relations/BelongsTo.ts, src/attributes/relations/BelongsToMany.ts, src/attributes/relations/HasMany.ts, src/attributes/relations/HasManyBy.ts, src/attributes/relations/HasManyThrough.ts, src/attributes/relations/HasOne.ts, src/attributes/relations/MorphMany.ts, src/attributes/relations/MorphOne.ts, src/attributes/relations/MorphTo.ts, src/attributes/relations/MorphToMany.ts, src/attributes/relations/MorphedByMany.ts, src/attributes/relations/Relation.ts, src/repo/Query.ts, src/repo/Repo.ts, test/feature/relations/Relations_MorphToMany.spec.js, test/performance/Retrieve_BelongsToMany.spec.js, test/performance/Retrieve_HasMany.spec.js, test/unit/repo/repo/Repo_Retrieve_Relations.spec.js, test/unit/repo/repo/Repo_Retrieve_Relations_MorphOne.spec.js
Issue #113 
This PR drastically improves the performance when loading a large amount of relational data.
However, this PR will introduce some breaking changes on `has` and `hasNot` constraint.
Because there was a huge change in relation loading method, I had to separate `has` method for counting the record, and filtering the record.
In short, when a user wants to check relationship existence with the relationship count, a user must use `has` method. On the other hand, when a user wants to check relation existence with the value of the related record, a user must use `whereHas` method (the new method).
```js
store.getters['entities/users/query']().has('posts', 3).get()
store.getters['entities/users/query']().whereHas('posts', (post) => {
post.where('published', true)
}).get()
```
=> #113 Improve performance when loading many relationships

src/attributes/relations/MorphToMany.ts, test/feature/relations/Relations_MorphToMany.spec.js
Issue #119
This PR fixes where creating morph to many without relation field is failing.
=> #119 Fix where creating morph to many without relation field is failing

src/data/PivotCreator.ts, test/unit/query/query/Query_Create_BelongsToMany.spec.js
Fix for issue #113.
Fixes nested many to many relationship failing to create pivot table.
The solution is based on reading the keys of the normalized data, fetching the models for each key and creating the pivot tables accordingly. (Thanks to @kiaking, that suggested the solution)
=> Fixes issue #113

src/attributes/relations/BelongsToMany.ts, src/data/processors/PivotCreator.ts, test/feature/relations/Relations_BelongsToMany.spec.js
Issue #137 
This PR fixes where the pivot table for the belongsToMany relation won't get created if the name of the key that defines the relation is different from the entity name of the related model.
=> #137 Fix where pivot table for the belongs to many not being created in certain case

docs/advanced/accessors-and-mutators.md, docs/components/models.md, src/attributes/contracts/Contract.ts, src/attributes/contracts/Type.ts, src/attributes/types/Boolean.ts, src/attributes/types/Number.ts, src/attributes/types/String.ts, src/attributes/types/Type.ts, src/model/Model.ts, test/feature/attributes/Boolean.spec.js, test/feature/attributes/Number.spec.js, test/feature/attributes/String.spec.js, test/unit/model/Model_Attributes_Boolean.spec.js, test/unit/model/Model_Attributes_Number.spec.js, test/unit/model/Model_Attributes_String.spec.js
Issue #110 
This PR adds specific type attributes that can be defined as model fields such as `this.string` or `this.number`.
=> #110 Add specific type attributes

src/query/Query.ts, test/feature/retrieve/Retrieve.spec.js
Issue #126 
This PR makes the `find` method return null when passing undefined as the argument.
=> #126 Return null when no argument passed to the `find` method

docs/advanced/interact-with-store-from-model.md, src/model/Model.ts, src/modules/Payloads.ts, src/modules/subActions.ts, test/feature/models/All.spec.js, test/feature/models/Create.spec.js, test/feature/models/Delete.spec.js, test/feature/models/Find.spec.js, test/feature/models/Insert.spec.js, test/feature/models/InsertOrUpdate.spec.js, test/feature/models/Query.spec.js, test/feature/models/Update.spec.js
Issue #60 
This PR adds convenience methods to the model where you can dispatch actions or getters such as `create` and `find`.
=> #60 Add convenience model methods

docs/guide/components/modules-and-store.md, docs/guide/relationships/retrieving-relationships.md, test/feature/relations/Retrieve_With_NestedConstraints.spec.js
Issue #104
This PR will add ability for the `with` relationship to be able to define constraints to the nested relations. It also works for when you define multiple constraint by chaining `with` method many times.
```js
// This is going to work now.
const users = store.getters['entities/users']().
.with('posts.comments', query => { ... })
.with('posts.likes', query => { ... })
.get()
```
=> #104 Nested `with` constraints

docs/guide/digging-deeper/plugins.md
I noticed (thx @phortx) that the Guide doesn't reflect the recent changes in names for the components available in the ``install`` method of a plugin. Submitting a PR.
=> updated Guide > Plugins section with the current list of components

src/attributes/relations/MorphMany.ts, test/feature/relations/MorphMany.spec.js
Issue: #216
This PR fixs error when trying to insert morph many relation with value of null.
=> #216 Fix error when trying to insert morph many relation with value of null

docs/api/model.md, src/model/Model.ts, test/unit/model/Model.spec.js
Issue: #240
This PR adds `hydrate` method to Model. Which will fill any missing fields in the given record with the default value defined in the model schema. This method will ignore any "relationship" fields such as `hasMany` or `belongsTo` and return only non-relational fields.
@okatsuralau Is this spec good enough for you? (please take a look at test cases).
=> #240 Add hydrate method

docs/guide/advanced/interact-with-store-from-model.md, src/database/Database.ts, src/model/Model.ts, src/model/State.ts, src/modules/RootMutations.ts, src/modules/builder/Builder.ts, src/modules/payloads/RootMutations.ts, test/feature/basics/State.spec.js
This PR adds ability to define and interact state from Model. Basically you can do this.
```js
class User extends Model {
static entity = 'users'
static state = {
fetching: false
}
static fields () {
return { ... } 
}
}
User.commit((state) => {
state.fetching = true
})
```
=> Define and interact state from Model

docs/guide/advanced/lifecycle-hooks.md
The examples of lifecycle hook usage in the docs did not previously declare the model hook handlers as static methods.
=> Updated lifecycle hook examples in the docs

src/model/Model.ts, test/unit/model/Model.spec.js
Issue #255
This PR will fix `non-POJP` warning when using Vuex ORM with Nuxt universal mode. See the issue for more details.
=> #255 Add toJSON method to fix Nuxt `non-POJO` warning

README.md
The inserting example uses `User.insert()` to insert the `posts` data. I think this is invalid. I had to change it to `Post.insert()` to make it work.
=> Invalid class in inserting example

src/attributes/relations/MorphToMany.ts, test/feature/relations/MorphToMany_Persist.spec.js
fix: https://github.com/vuex-orm/vuex-orm/issues/258
Hi @kiaking 
Cause is this.increment() to Taggable's id field, but I don't know is need to fix this problem, because pivot data isn't set to insertOrUpdate.
=> morphToMany relation duplicates the pivot records

docs/guide/relationships/retrieving-relationships.md, src/query/loaders/Loader.ts, test/feature/relations/Retrieve_With.spec.js
Following suggestion on Slack, I added the possibility to pass an array of relations to the `query.with()` loader.
=> Adding array handling for query.with

test/feature/relations/BelongsToMany_Retrieve.spec.js
Issue #270 
Trying to reproduce the problem but the test case is passing...
=> #270 Fix belongsTo relationship returning `undefined` when relation is not found.

docs/guide/components/models.md, src/attributes/types/Attr.ts, test/unit/model/Model.spec.js
`this.attr()` now accepts closure as a first argument to create default values
=> Adding a way to pass a closure as a default value

src/query/processors/IdFixer.ts, test/feature/basics/Insert.spec.js
Issue #304
This PR fixes the `toString` error when trying to insert a record with primary key value of `null`.
=> #304 Fix `toString` error when the primary key value is `null`

src/attributes/relations/MorphToMany.ts, test/feature/relations/MorphToMany_Persist.spec.js
Issue #367
This PR fixes issue that wrong id value being generated when inserting records with morphToMany relationship with all models using `increment` attribute.
=> #367 Fix where creating morph to many record with incremented id not working correctly

src/model/Model.ts, test/unit/model/Model_Utilities.spec.js
Issue #319 
This PR fixes where the current `toJSON` method is not compatible with `JSON.stringify`. The method is now going to return every property of the model instance (not only field that is defined in `static fields`).
=> #319 Fix toJSON was not compatible with JSON.stringify

src/attributes/relations/HasManyThrough.ts, test/feature/relations/HasManyThrough.spec.js
Issue #410
This PR fixes `hasManyThrough` relationship returning array of undefined when target entity is empty.
=> #410 Fix `hasManyThrough` relationship returning array of undefined when target entity is empty

src/attributes/relations/HasManyBy.ts, test/feature/relations/HasManyBy.spec.js
Issue #391
This PR fixes the error that hasManyBy relationship throwing error when trying to pass null at related field.
=> #391 Fix hasManyBy relationship throwing error when trying to pass null at related field

docs/.vuepress/config.js, docs/guide/data/inserting-and-updating.md
Because of the length of some of the docs (not a bad thing at all!), it can be difficult to find the specific topic you are looking for. Including the <h3> headers in the sidebar makes this much easier.
=> change sidebar depth to 2

src/query/Query.ts, test/feature/basics/Retrieve.spec.js
Issue #504
This PR fixes where the `first` and the `last` method returning `undefined` when data is empty. It should return `null`, and it will now.
=> #504 Fix first and last method returning undefined on empty result

src/attributes/relations/BelongsToMany.ts, test/feature/relations/BelongsToMany_Persist.spec.js
There should not be restrictions in which order pivot tables composite key fields are.
BelongsToMany#createPivotRecord assumed that relates-to tables key was always first. Other parts of the code used correct order => created issues with store indexes.
=> fix: pivot table composite key can be in any order

docs/api/container/container.md, docs/api/database/database.md, docs/api/model/model.md, docs/guide/data/deleting.md, docs/guide/data/inserting-and-updating.md, docs/guide/digging-deeper/plugins.md, src/model/Model.ts, test/feature/basics/New.spec.js, test/feature/relations/MorphToMany_Persist.spec.js, test/unit/model/Model.spec.js
This PR attempts to dissipate the already deprecated `increment` attribute in the documentation and unit tests.
The attribute `increment` has been replaced by the newly promoted `uid` attribute and it makes sense to warn users who update to future releases.
There are various other grammatical and type corrections thrown in for good measure.
=> Remove deprecated functionality references from docs/tests

src/database/Database.ts
This PR fixes an incomprehensible exception thrown when attempting to register a model that references an absent one (either it was not registered or doesn't exist) or context based retrieval.
Exception thrown:
```
[Vuex ORM] Could not find the model ``. Please check if you have registered the model to the database.
```
Previously it stated the suspect model entity but an undeclared variable in the error message prohibits this.
Model definition:
```
class User extends Model {
static entity = 'users';
static fields() {
return {
id: this.attr(null),
role: this.hasOne('nonregistered')
}
}
}
```
Context based:
```
new Database().model('nonregistered')
$store.$db().model('nonregistered')
```
=> Incomprehensible exception thrown due to missing var `name`

docs/guide/data/inserting-and-updating.md, docs/guide/model/relationships.md, src/attributes/relations/BelongsToMany.ts, src/attributes/relations/MorphToMany.ts, src/attributes/relations/MorphedByMany.ts, src/model/Model.ts, test/feature/relations/BelongsToMany_Persist.spec.js, test/feature/relations/MorphToMany_Persist.spec.js, test/feature/relations/MorphedByMany_Persist.spec.js
This PR is built on top of #542. It adds `as` method to many-to-many relationship attribute to let users customize `pivot` key name.
```js
class User extends Model {
static entity = 'users'
static fields () {
return {
id: this.attr(null),
podcasts: this.belongsToMany(
Podcast,
Subscription,
'user_id',
'podcast_id'
).as('subscription')
}
}
}
const user = User.query().with('podcasts').first()
user.podcasts.forEach((podcast) => {
console.log(podcast.subscription)
})
```
@cuebit Could you check mainly at the documentations whether it's easy to understand this feature? 😃
=> feat: add `as` method to customize `pivot` attribute name

docs/guide/data/retrieving.md, docs/guide/prologue/what-is-vuex-orm.md
Updating broken link to article: Redux Normalizing State Shape documentation.
From: http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html
To: https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape/
=> Fix broken link to Normalizing State Shape article and composite primary key example

src/query/Query.ts, test/feature/relations/Retrieve_With.spec.js
This PR fixes the `findIn` method not resolving child relations like its counterpart `find` does. Resolves #588.
Consider the following:
```js
User.insert({
id: 1,
posts: [{ id: 1 }, { id: 2 }]
})
User.query().with('posts').findIn([1, 2])
```
Current behavior:
```js
[
{
$id: 1,
id: 1,
posts: []
}
]
```
Behavior changes in this PR:
```js
[
{
$id: 1,
id: 1,
posts: [
{ $id: 1, id: 1 },
{ $id: 2, id: 2 }
]
}
]
```
=> fix(query): `findIn` should resolve child relations

src/attributes/relations/BelongsTo.ts, src/attributes/relations/BelongsToMany.ts, src/attributes/relations/HasMany.ts, src/attributes/relations/HasManyBy.ts, src/attributes/relations/HasManyThrough.ts, src/attributes/relations/HasOne.ts, src/attributes/relations/MorphMany.ts, src/attributes/relations/MorphOne.ts, src/attributes/relations/MorphTo.ts, src/attributes/relations/MorphToMany.ts, src/attributes/relations/MorphedByMany.ts, src/attributes/relations/Relation.ts, test/feature/basics/Retrieve.spec.js, test/feature/relations/BelongsToMany_Retrieve.spec.js, test/feature/relations/HasManyBy.spec.js, test/feature/relations/MorphMany_Retrieve.spec.js, test/feature/relations/MorphToMany_Retrieve.spec.js, test/feature/relations/MorphedByMany_Retrieve.spec.js, test/unit/support/Utils.spec.ts
Resolves #571 it is reported that nested relations do not observe any ordering constraints applied to them.
- Applying `orderBy` constraint on nested relations is ignored and relationships are loaded in the order in which they were inserted.
- In some cases where primary keys are integers, the ordering is unreliable because numeric object keys do not preserve the order in which the dictionary is created.
- Use [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) to generate relation indexes to make sure the ordering is preserved for numeric keys. 
- Only iterate over recursive relations if the relation query contains any order constraints to avoid expensive iterations for relations without.
=> fix: nested relationship orderBy constraints

src/attributes/relations/BelongsToMany.ts, src/attributes/relations/MorphToMany.ts, src/attributes/relations/MorphedByMany.ts, src/attributes/relations/Relation.ts, src/model/Model.ts, src/model/Serialize.ts, src/modules/Actions.ts, src/query/Query.ts, src/query/filters/WhereFilter.ts, src/query/loaders/Loader.ts, src/query/processors/Normalizer.ts, src/query/rollcallers/Rollcaller.ts, src/schema/IdAttribute.ts, src/support/Utils.ts
When checking a value is a type of array, using `foo instanceof Array` was causing false negative in Nuxt server side env. It's fixed by using `Array.isArray()` instead.
This PR adds `isArray` utility function, and replaces all `Array.isArray()` and `foo instanceof Array` condition checks.
=> fix: use `isArray` util function to check the type of the array

src/query/processors/Normalizer.ts
This PR removes `deepCopy` inside normalizer. Since deep copy is done at `persist` method [at here](https://github.com/vuex-orm/vuex-orm/blob/3a2f77000b21df83d2925030445f9a350b835091/src/query/Query.ts#L1040), I think it's unnecessary to do it here.
@cuebit Could you check if this looks ok?
=> refactor(query): remove double deep copy

docs/guide/data/retrieving.md, src/query/Query.ts, src/query/loaders/Loader.ts, test/feature/relations/Retrieve_With_NestedConstraints.spec.ts
This PR resolves #603.
Wildcard relation loading invokes `withAll` immediately but does not observe any constraint(s) that may exist. This PR passes on any constraint(s) to the invokable and resolves as a **bugfix**.
Moreover, this means the `withAll` query method can observe constraints. Since this was not previously possible, it can be classified as a new **feature**.
Furthermore, the **documentation** has been updated to include an example of how constraints can be applied to both `withAll` and wildcard relation queries.
=> fix: wildcard relations should observe constraints (#603)

src/database/Database.ts
This PR aims to decrease the complexity of getting a single model/baseModel from the entities list, as described in the issue #717.
It basically replaces the two reduces found [here](https://github.com/vuex-orm/vuex-orm/blob/7573d2fe92c45fbf455e780222e9029e7267f2cd/src/database/Database.ts#L100) and [here](https://github.com/vuex-orm/vuex-orm/blob/7573d2fe92c45fbf455e780222e9029e7267f2cd/src/database/Database.ts#L119) with the javascript [find](https://www.w3schools.com/jsref/jsref_find.asp) to retrieve a model/baseModel from a list of entities.
=> Improving performance of getting a model/baseModel from entities
